/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo.o.o;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 20171INF_I0238
 */
public class Criar extends javax.swing.JFrame {
    public int Forca = 1, Velocidade = 1, Energia = 1, Visao = 1, Resistencia = 1, Altura = 150;
    String Nome = "", Habilidade;
    Texto TEX = new Texto();
    
    public Criar() {
        initComponents();
        getContentPane().setBackground(new Color(102, 102, 102));
        
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bt_voltar = new javax.swing.JButton();
        br_altura = new javax.swing.JSlider();
        tx_altura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rb_homem = new javax.swing.JRadioButton();
        rb_mulher = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cb_habilidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jl_forca = new javax.swing.JLabel();
        jl_velocidade = new javax.swing.JLabel();
        jl_visao = new javax.swing.JLabel();
        jl_resistencia = new javax.swing.JLabel();
        jl_energia = new javax.swing.JLabel();
        bt_pronto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        bt_voltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_voltar);
        bt_voltar.setBounds(50, 500, 150, 50);

        br_altura.setMaximum(215);
        br_altura.setMinimum(150);
        br_altura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                br_alturaMouseDragged(evt);
            }
        });
        getContentPane().add(br_altura);
        br_altura.setBounds(500, 110, 150, 30);

        tx_altura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tx_altura.setText("150 cm");
        getContentPane().add(tx_altura);
        tx_altura.setBounds(610, 70, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Altura:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 50, 110, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 50, 115, 44);

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome);
        tf_nome.setBounds(170, 65, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Genero:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 130, 44);

        buttonGroup1.add(rb_homem);
        rb_homem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_homem.setSelected(true);
        rb_homem.setText("Masculino");
        getContentPane().add(rb_homem);
        rb_homem.setBounds(200, 170, 150, 50);

        buttonGroup1.add(rb_mulher);
        rb_mulher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb_mulher.setText("Feminino");
        getContentPane().add(rb_mulher);
        rb_mulher.setBounds(200, 230, 150, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Habilidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 350, 130, 29);

        cb_habilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha...", "Aprende Rápido", "Sou Raiz, Não Nutella", "Duro como Pedra", "Mais Esforço", "Visão de Águia", "Eu sou He-Man", "Só pode ser o Flash" }));
        cb_habilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_habilidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cb_habilidade);
        cb_habilidade.setBounds(180, 345, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Atributos:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 200, 160, 44);

        jl_forca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_forca.setText("Força: 1");
        getContentPane().add(jl_forca);
        jl_forca.setBounds(500, 250, 100, 22);

        jl_velocidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_velocidade.setText("Velocidade: 1");
        getContentPane().add(jl_velocidade);
        jl_velocidade.setBounds(500, 300, 120, 22);

        jl_visao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_visao.setText("Visão: 1");
        getContentPane().add(jl_visao);
        jl_visao.setBounds(500, 400, 100, 22);

        jl_resistencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_resistencia.setText("Resistencia: 1");
        getContentPane().add(jl_resistencia);
        jl_resistencia.setBounds(500, 450, 130, 22);

        jl_energia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_energia.setText("Energia: 1");
        getContentPane().add(jl_energia);
        jl_energia.setBounds(500, 350, 130, 22);

        bt_pronto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_pronto.setText("Pronto");
        bt_pronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prontoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_pronto);
        bt_pronto.setBounds(600, 500, 150, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        Inicio frame1 = new Inicio();
        frame1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void br_alturaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_br_alturaMouseDragged
        Altura = br_altura.getValue();
        tx_altura.setText(String.valueOf(Altura) + " cm");
    }//GEN-LAST:event_br_alturaMouseDragged

    private void cb_habilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_habilidadeActionPerformed
        Forca = 1; 
        Velocidade = 1;
        Energia = 1;
        Visao = 1;
        Resistencia = 1;
        if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Aprende Rápido"){
            
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Sou Raiz, Não Nutella"){
            
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Duro como Pedra"){
            Resistencia = 10;
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Mais Esforço"){
            Energia = 10;
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Visão de Águia"){
            Visao = 10;
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Eu sou He-Man"){
            Forca = 10;
        }else if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) == "Só pode ser o Flash"){
            Velocidade = 10;
        }
        jl_forca.setText("Força: "+String.valueOf(Forca));
        jl_velocidade.setText("Velocidade: "+String.valueOf(Velocidade));
        jl_energia.setText("Energia: "+String.valueOf(Energia));
        jl_visao.setText("Visão: "+String.valueOf(Visao));
        jl_resistencia.setText("Resistencia: "+String.valueOf(Resistencia));
    }//GEN-LAST:event_cb_habilidadeActionPerformed

    private void bt_prontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prontoActionPerformed
        if(Nome != ""){
        if(cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex()) != "Escolha..."){
        Habilidade = cb_habilidade.getItemAt(cb_habilidade.getSelectedIndex());
        TEX.StatusSalvar(Forca, Velocidade, Energia, Visao, Resistencia, Altura, Nome, Habilidade);
        Menu frame2 = new Menu();
        frame2.setVisible(true);
        this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Faltou a habilidade selecionada!!!");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Faltou o nome!!!");
        }
    }//GEN-LAST:event_bt_prontoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        Nome = tf_nome.getText();
    }//GEN-LAST:event_tf_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Criar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider br_altura;
    private javax.swing.JButton bt_pronto;
    private javax.swing.JButton bt_voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_habilidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jl_energia;
    private javax.swing.JLabel jl_forca;
    private javax.swing.JLabel jl_resistencia;
    private javax.swing.JLabel jl_velocidade;
    private javax.swing.JLabel jl_visao;
    private javax.swing.JRadioButton rb_homem;
    private javax.swing.JRadioButton rb_mulher;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JLabel tx_altura;
    // End of variables declaration//GEN-END:variables
}
